# Site settings
name: Voliet's blog
email: xuzh9310@163.com
author: Voliet
# url: http://www.hifreud.com
# resume_site: http://www.hifreud.com/Resume.io/
github: https://github.com/voiletXu/
baseurl: "/voiletXu.github.io"
description: Code is Poetry, Poetry is Beautiful!
meta_description: voiletXu;个人博客;喜欢在代码中游走，也喜欢拥抱大自然！
motto: Code is Poetry, Poetry is Beautiful!
banner: 与时俱进，“码”出未来

#permalink: /:categories/:year/:month/:day/:title/
permalink: /:year/:month/:day/:title/
paginate: 10

exclude: ['README.md', 'Gemfile.lock', 'Gemfile', 'Rakefile']

# github_username: luoyan35714

# Build settings
markdown: kramdown

baidu_analysis: 94be4b0f9fc5d94cc0d0415ea6761ae9

